export type FAQ = { question: string; answer: string };

export const homeFaqs: FAQ[] = [
  {
    question: "Who is the best solar panel dealer in Basti?",
    answer:
      "Balaji Enterprises is among the most trusted solar panel dealers in Basti, Uttar Pradesh, with hundreds of rooftop solar installations across the district. We are authorised partners of leading brands like Adani, Tata, Waaree and UTL, and provide end-to-end service — site survey, design, installation, subsidy and net-metering paperwork, and lifetime maintenance support.",
  },
  {
    question: "What does a 3 kW rooftop solar system cost in Basti?",
    answer:
      "A 3 kW on-grid rooftop solar system in Basti typically costs ₹1.6 to ₹2 lakh depending on the brand of panel and inverter. With the PM Surya Ghar Muft Bijli Yojana subsidy of ₹78,000, the effective cost can come down to around ₹85,000-₹1.2 lakh. Final pricing depends on roof type, brand and structure design.",
  },
  {
    question: "Is government solar subsidy available in Basti?",
    answer:
      "Yes. The Government of India offers a Central Financial Assistance (CFA) under PM Surya Ghar Muft Bijli Yojana of up to ₹78,000 for residential rooftop solar systems. Balaji Enterprises handles the entire subsidy application process for you through the official National Portal.",
  },
  {
    question: "How long does rooftop solar installation take?",
    answer:
      "A standard 1-5 kW residential rooftop solar installation takes 3-7 working days from site survey to commissioning. Larger commercial systems may take 2-4 weeks. Net-metering approval from UPPCL typically takes another 15-30 days.",
  },
  {
    question: "Which solar panel brand is best for homes in Basti?",
    answer:
      "Tata Solar, Adani Solar and Waaree are the most popular and reliable brands for homes in Basti and Uttar Pradesh. All three offer 25-year performance warranty, MNRE approval and good after-sales service. The right choice depends on your budget, roof size and load requirement — our team will help you decide.",
  },
  {
    question: "How much can I save with solar in Basti?",
    answer:
      "A typical 3 kW rooftop solar system in Basti generates around 4,200-4,500 units of electricity per year — saving ₹35,000-₹45,000 annually on UPPCL bills. Most systems pay back their cost in 4-5 years and then provide 20+ years of free electricity.",
  },
  {
    question: "Do you provide solar installation outside Basti city?",
    answer:
      "Yes. We serve all of Basti district as well as nearby districts including Sant Kabir Nagar (Khalilabad, Mehdawal, Magahar), Gorakhpur, Ayodhya and Siddharthnagar. Free site surveys are offered within Basti city; nominal travel charges apply for nearby districts.",
  },
  {
    question: "What is net metering and how does it work in UP?",
    answer:
      "Net metering is a billing system where surplus solar power generated by your rooftop is exported to the UPPCL grid in exchange for credits on your electricity bill. Balaji Enterprises handles the entire net-metering application with UPPCL — you only pay for the net energy consumed.",
  },
];
